### ISSUE TITLE
HGDP is hardcoded as the data set for gglob genotyper Snakefile rule "get_long_table"

### ISSUE THREAD

**Issue by huddlej** [bnelsj/read_depth_genotyper#1]
See line 51 of Snakefile for gglob_genotyper:

shell("""Rscript transform_genotypes.R {input.regions} {pop_file} {pop_codes} hgdp {output}""")

**Comment by bnelsj** [comment]
Should be fixed in the latest commit. Eventually, these variables will be incorporated into a config file that works for both genotyping modes.
